# Default values for elastic-stack.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

elasticSearch:
  version: 7.16.2
  masterNodesCount: 1
  dataNodesCount: 2

  storageClass:
    name: "scw-bssd" ## default in scaleway

kibana:
  version: 7.16.2
  replicasCount: 1

nameOverride: ""
fullnameOverride: ""

podSecurityContext: {}

elasticAutoscaling:
  enabled: false
  config:
    nodeCount:
      min: 2
      max: 7
    cpu:
      min: 2
      max: 8
    memory:
      min: 2Gi
      max: 8Gi
    storage:
      min: 64Gi
      max: 512Gi

nodeSelector: {}

tolerations: []

ingress: {}
