{{- if semverCompare "<8.0.0" .Values.elasticSearch.version -}}
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: {{ include "elastic-stack.fullname" . }}
  labels:
    {{- include "elastic-stack.labels" . | nindent 4 }}
spec:
  # image: {{ .Values.elasticSearch.image }}
  version: {{ .Values.elasticSearch.version }}
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  podDisruptionBudget:
    spec:
      minAvailable: 2
      selector:
        matchLabels:
          elasticsearch.k8s.elastic.co/cluster-name: {{ include "elastic-stack.fullname" . }}
  nodeSets:
  - name: default
    count: {{ add .Values.elasticSearch.dataNodesCount .Values.elasticSearch.masterNodesCount }}
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          readinessProbe:
            exec:
              command:
              - bash
              - -c
              - /mnt/elastic-internal/scripts/readiness-probe-script.sh
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 12
            successThreshold: 1
            timeoutSeconds: 12
          env:
          - name: ES_JAVA_OPTS
            value: -Xms2g -Xmx2g
          resources:
            limits:
              memory: 4Gi
              cpu: 500m
            requests:
              memory: 4Gi
              cpu: 500m
        initContainers:
        - name: install-plugins
          command:
          - sh
          - -c
          - |
            bin/elasticsearch-plugin install --batch repository-s3
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100 # anti-affinity rule: prevent 2 nodes from beig scheduled on the same host
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    elasticsearch.k8s.elastic.co/cluster-name: {{ include "elastic-stack.fullname" . }}
                topologyKey: kubernetes.io/hostname
    config:
      # xpack.ml.enabled: true
      # index.store.type: hybridfs # pick the best storage system for lucene indices
      node.store.allow_mmap: false # virtual memory custmization (turn on when previleged container not working)
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
        storageClassName: {{ .Values.elasticSearch.storageClass.name }}
{{- end }}


## CRD documentation through `kubectl describe crd elasticsearch`

# See roles https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-node.html
# see nodes affinity https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-advanced-node-scheduling.html