apiVersion: autoscaling.k8s.elastic.co/v1alpha1
kind: ElasticsearchAutoscaler
metadata:
  name: autoscaler
spec:
  ## The name of the Elasticsearch cluster to be scaled automatically.
  elasticsearchRef:
    name: {{ include "elastic-stack.fullname" . }}
    labels:
      {{- include "elastic-stack.labels" . | nindent 4 }}
  ## The autoscaling policies.
  policies:
    - name: data-ingest
      roles: ["data", "ingest" , "transform"]
      resources:
        {{- toYaml .Values.elasticAutoscaling | nindent 12 }}